name: Publish slides

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    container: rocker/tidyverse:4.5.2
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v6
      
      - name: Install system dependencies
        run: |
          apt-get update && apt-get install -y --no-install-recommends \
          libxt6 libglpk-dev gh curl jq rsync

      - name: Install Chrome
        run: |
          curl -LO https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
          sudo rm google-chrome-stable_current_amd64.deb

      - name: Install packages from renv.lock (with cache)
        if: ${{ !env.ACT }}  
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 2

      - name: Install packages from renv.lock (local, no cache)
        if: ${{ env.ACT }}  
        run: |
          renv::restore()
        shell: Rscript {0}
        
      - name: Render slides and PDF
        run: |
          source("_render_slides.R")
        shell: Rscript {0}
      
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
